### ISSUE TITLE
Unable to load class com.github.tcnh.fitnesse.responders.AutoCompleteResponde

### ISSUE THREAD

**Issue by RachidKhe** [tcnh/fitnesse-bootstrap-plus-theme#2]
I'm using hsac fitnesse fixture and want to use autocomplete. when i add Responders=autoComplete:com.github.tcnh.fitnesse.responders.AutoCompleteResponder to my plugins.properties file and build I get follwoing error
[INFO] --- exec-maven-plugin:1.5.0:exec (default-cli) @ functioneletests ---
SEVERE: Error while starting the FitNesse [Unable to load class com.github.tcnh.fitnesse.responders.AutoCompleteResponde

I used  installation steps in option 2 of https://github.com/tcnh/fitnesse-bootstrap-plus-theme

**Comment by tcnh** [comment]
Did you include the autocomplete responder jar to your plugins directory (either by a copy-resources maven step or a manual copy?)

**Comment by tcnh** [comment]
Note that when using the latest hsac version, there is also a 2018 version of fitnesse included. This version has a bug that makes loading bootstrap-based themes impossible. See: https://github.com/unclebob/fitnesse/issues/1124

As a workaround, until the issue is resolved, you could use: https://search.maven.org/#artifactdetails%7Ccom.github.tcnh%7Cfitnesse%7C20180425%7Cjar 
(I uploaded my fixed branch to maven central so that my projects could continue using hsac with the latest browsers and bootstrap-plus)

**Comment by tcnh** [comment]
This is fixed in FitNesse v 20190127
