### ISSUE TITLE
fitnesse 20180127

### ISSUE THREAD

**Issue by roydekleijn** [tcnh/fitnesse-bootstrap-plus-theme#3]
Hello,

How does this work with fitnesse 20180127 ? By default the CSS doesn't load.

![image](https://user-images.githubusercontent.com/1298389/47144678-4227d900-d2c8-11e8-8e39-c440dabfcf97.png)

With version 20171210 it works in one go.

Best regards,
Roy

**Comment by tcnh** [comment]
It doesn't. Support for loading resources from a jar was broken in the classpath fixes done in december 2017.
See: https://github.com/unclebob/fitnesse/pull/1127

Because there is zero activity in the original repo, I've created a fixed version under my own groupid. You could use that one until the above PR gets merged.

```
<dependency>
  <groupId>com.github.tcnh</groupId>
  <artifactId>fitnesse</artifactId>
  <version>20180817</version>
</dependency>
```

**Comment by roydekleijn** [comment]
Thanks for the prompt answer
